version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: quackoloc.db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: zYxvaMVbyxBaW@Hz10Nm
      POSTGRES_DB: quackoloc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
