name: Build and Deploy to VPS

on:
  push:
    branches:
      - main
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build and push API image
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_OWNER/quackoloc-api:latest -f ./Dockerfile .
          docker push ghcr.io/$REPO_OWNER/quackoloc-api:latest

      - name: Cleanup .env file
        run: rm .env

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Convert repository owner to lowercase
        run: echo "GITHUB_REPO_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Pull and Run Docker Containers on VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          ssh root@${{ env.VPS_IP }} "
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PAT_TOKEN }}
            docker pull ghcr.io/${{ GITHUB_REPO_OWNER }}/quackoloc-api:latest
            docker stop quackoloc-api || true && docker rm quackoloc-api || true
            docker run -d --name quackoloc-api -p 3000:3000 ghcr.io/${{ GITHUB_REPO_OWNER }}/quackoloc-api:latest
          "
