name: Build and Deploy to Clever Cloud

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm run test:cov
      - name: Write to Job Summary
        run: |
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f coverage/coverage-summary.json ]; then
            echo "| Metric | Coverage |" >> $GITHUB_STEP_SUMMARY
            echo "|--------|----------|" >> $GITHUB_STEP_SUMMARY
            cat coverage/coverage-summary.json | jq -r '
              "| Lines | " + (.total.lines.pct | tostring) + "% |",
              "| Functions | " + (.total.functions.pct | tostring) + "% |", 
              "| Branches | " + (.total.branches.pct | tostring) + "% |",
              "| Statements | " + (.total.statements.pct | tostring) + "% |"
            ' >> $GITHUB_STEP_SUMMARY
          else
            echo "Coverage data not available" >> $GITHUB_STEP_SUMMARY
          fi

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
    outputs:
      image-tag: ${{ steps.meta.outputs.tag }}
      repo-owner: ${{ steps.meta.outputs.repo-owner }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
      - name: Inject .env from GitHub secret
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Set image metadata
        id: meta
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          TAG=$(git rev-parse --short HEAD)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "repo-owner=$REPO_OWNER" >> $GITHUB_OUTPUT
      - name: Build and push API image
        run: |
          REPO_OWNER=${{ steps.meta.outputs.repo-owner }}
          TAG=${{ steps.meta.outputs.tag }}
          docker build --no-cache -t ghcr.io/$REPO_OWNER/quackoloc.api:$TAG -f ./dockerfiles/build.Dockerfile .
          docker tag ghcr.io/$REPO_OWNER/quackoloc.api:$TAG ghcr.io/$REPO_OWNER/quackoloc.api:latest
          docker push ghcr.io/$REPO_OWNER/quackoloc.api:$TAG
          docker push ghcr.io/$REPO_OWNER/quackoloc.api:latest

  semantic-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build-docker
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  deploy-clever:
    runs-on: ubuntu-latest
    needs: [ build-docker ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Clever Tools
        run: npm install -g clever-tools
      - name: Login and trigger deploy
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        run: |
          clever login --token "$CLEVER_TOKEN" --secret "$CLEVER_SECRET"
          clever link app_bcb853ad-7de5-4deb-be7d-a4f0b0d4e41b
          clever restart
